F
======================================================================
FAIL: test_stop (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_4.py", line 11, in test_stop
    self.assertEqual(functions.main_loop(name, "hola", "vaca", "oso", "stop!"), expected_output)
AssertionError: None != '¡Buenas noches Anibal!\naloh\nacav\n¡Bonita palabra!\nAdios stop!!'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)